---

- name: Install packages
  tags: packages searx
  apt: name={{ packages }} state=present
  vars:
    packages:

- name: Install system dependencies
  tags: searx
  apt: name={{ packages }} state=present
  vars:
    packages:
      - git
      - build-essential
      - libxslt-dev
      - python-cffi
      - python-dev
      - python-virtualenv
      - python-babel
      - zlib1g-dev
      - libffi-dev
      - libssl-dev
      - uwsgi
      - uwsgi-plugin-python
      - nginx # TODO: Make this configurable

- name: Clone searx from GitHub - version {{ searx_version }}.
  tags: searx
  git: 
    repo: https://github.com/asciimoo/searx.git
    dest: '{{ searx_install_path }}'
    update: no
    version: '{{ searx_version }}'

- name: Create a new user, {{ searx_user }}.
  tags: searx
  user:
    name: '{{ searx_user }}'
    system: yes 
    createhome: no
    home: '{{ searx_install_path }}'

- name: Correct Permissions
  tags: searx
  file: 
    path: '{{ searx_install_path }}'
    owner: '{{ searx_user }}'
    group: '{{ searx_user }}'
    recurse: yes

- block:  
  - name: Install python virtual enviromnet dependencies
    tags: searx
    pip:
      virtualenv: searx-ve
      virtualenv_site_packages: yes
      virtualenv_python: python2.7
      requirements: requirements.txt
      extra_args: '--no-cache-dir'
      chdir: '{{ searx_install_path }}'
    vars:
      ansible_ssh_pipelining: yes

  - name: Configure secrect key
    tags: searx
    replace:
      dest: '{{ searx_install_path }}/searx/settings.yml'
      regexp: ultrasecretkey
      replace: '{{ searx_secret }}'

    become: yes
    become_user: '{{ searx_user }}'
    vars:
      ansible_ssh_pipelining: yes

- name: SystemD Service
  tags: searx
  template: src=searx.service dest=/etc/systemd/system/searx.service

- name: Enabeling and starting searx
  tags: searx
  service:
    name: searx
    state: started
    enabled: yes

- name: Add uwsgi config
  tags: searx
  template: src=searx.ini.j2 dest=/etc/uwsgi/apps-available/searx.ini

- name: Enable searx with uwsgi
  tags: searx
  file: src=/etc/uwsgi/apps-available/searx.ini dest=/etc/uwsgi/apps-enabled/searx.ini owner=root group=root state=link
  notify: restart uwsgi

- name: Add nginx config
  tags: searx
  template: src=searx.conf.j2 dest=/etc/nginx/sites-available/searx.conf

- name: Enable searx with nginx
  tags: searx
  file: src=/etc/nginx/sites-available/searx.conf dest=/etc/nginx/sites-enabled/searx.conf owner=root group=root state=link
  notify: restart nginx
